export const STRATEGY_COLORS: Record<string, string> = {
  FIX_FLIP:            "rgba(127,119,221,0.3)",
  RENTA:               "rgba(29,158,117,0.3)",
  RENTAL_LONG_TERM:    "rgba(29,158,117,0.3)",
  FARMLAND:            "rgba(186,117,23,0.3)",
  DISTRESS:            "rgba(226,75,74,0.3)",
  DISTRESSED:          "rgba(226,75,74,0.3)",
  VALUE_ADD:           "rgba(127,119,221,0.25)",
  LAND_BANKING:        "rgba(186,117,23,0.25)",
  SHORT_TERM_RENTAL:   "rgba(29,158,117,0.25)",
  NNN_COMERCIAL:       "rgba(93,202,165,0.25)",
  GREENFIELD:          "rgba(99,153,34,0.3)",
  LIVESTOCK:           "rgba(186,117,23,0.2)",
  FORESTRY:            "rgba(99,153,34,0.25)",
  BUY_AND_HOLD:        "rgba(29,158,117,0.2)",
};

export const STRATEGY_LABELS: Record<string, string> = {
  FIX_FLIP:            "Fix & Flip",
  RENTA:               "Renta",
  RENTAL_LONG_TERM:    "Renta larga",
  FARMLAND:            "Farmland",
  DISTRESS:            "Distressed",
  DISTRESSED:          "Distressed",
  VALUE_ADD:           "Value Add",
  LAND_BANKING:        "Land Banking",
  SHORT_TERM_RENTAL:   "Short-term Rental",
  NNN_COMERCIAL:       "NNN Comercial",
  GREENFIELD:          "Greenfield",
  LIVESTOCK:           "Livestock",
  FORESTRY:            "Forestry",
  BUY_AND_HOLD:        "Buy & Hold",
};

// Métricas del Hero por estrategia
// topRight = siempre G-Score (universal)
export const HERO_METRICS_CONFIG: Record<string, {
  topLeft: { label: string; field: string; format: string; color: string };
  bottomLeft: { label: string; field: string; format: string; color: string };
  bottomRight: { label: string; field: string; format: string; color: string };
}> = {
  FIX_FLIP: {
    topLeft:    { label: "TIR",          field: "irr_equivalente",   format: "percent", color: "green" },
    bottomLeft: { label: "Riesgo",       field: "risk_score",        format: "score",   color: "amber" },
    bottomRight:{ label: "Margen bruto", field: "roiTotal",          format: "percent", color: "green" },
  },
  RENTA: {
    topLeft:    { label: "Cap Rate",     field: "irr_equivalente",   format: "percent", color: "green" },
    bottomLeft: { label: "Riesgo",       field: "risk_score",        format: "score",   color: "amber" },
    bottomRight:{ label: "NOI anual",    field: "ingreso_neto_anual",format: "currency",color: "green" },
  },
  RENTAL_LONG_TERM: {
    topLeft:    { label: "Cap Rate",     field: "irr_equivalente",   format: "percent", color: "green" },
    bottomLeft: { label: "Riesgo",       field: "risk_score",        format: "score",   color: "amber" },
    bottomRight:{ label: "NOI anual",    field: "ingreso_neto_anual",format: "currency",color: "green" },
  },
  FARMLAND: {
    topLeft:    { label: "Yield agro",   field: "irr_equivalente",   format: "percent", color: "amber" },
    bottomLeft: { label: "Riesgo",       field: "risk_score",        format: "score",   color: "amber" },
    bottomRight:{ label: "Renta/año",    field: "ingreso_neto_anual",format: "currency",color: "amber" },
  },
  DISTRESS: {
    topLeft:    { label: "IRR proy.",    field: "irr_equivalente",   format: "percent", color: "green" },
    bottomLeft: { label: "Riesgo",       field: "risk_score",        format: "score",   color: "red"   },
    bottomRight:{ label: "Descuento",    field: "descuento_pct",     format: "percent", color: "green" },
  },
  DISTRESSED: {
    topLeft:    { label: "IRR proy.",    field: "irr_equivalente",   format: "percent", color: "green" },
    bottomLeft: { label: "Riesgo",       field: "risk_score",        format: "score",   color: "red"   },
    bottomRight:{ label: "Descuento",    field: "descuento_pct",     format: "percent", color: "green" },
  },
  VALUE_ADD: {
    topLeft:    { label: "TIR",          field: "irr_equivalente",   format: "percent", color: "green" },
    bottomLeft: { label: "Riesgo",       field: "risk_score",        format: "score",   color: "amber" },
    bottomRight:{ label: "Upside",       field: "roiTotal",          format: "percent", color: "green" },
  },
  LAND_BANKING: {
    topLeft:    { label: "Apreciación",  field: "irr_equivalente",   format: "percent", color: "amber" },
    bottomLeft: { label: "Riesgo",       field: "risk_score",        format: "score",   color: "amber" },
    bottomRight:{ label: "Horizonte",    field: "horizonte_anos",    format: "number",  color: "white" },
  },
  SHORT_TERM_RENTAL: {
    topLeft:    { label: "RevPAR",       field: "irr_equivalente",   format: "percent", color: "green" },
    bottomLeft: { label: "Riesgo",       field: "risk_score",        format: "score",   color: "amber" },
    bottomRight:{ label: "Ocupación",    field: "ocupacion_pct",     format: "percent", color: "green" },
  },
  NNN_COMERCIAL: {
    topLeft:    { label: "Cap Rate",     field: "irr_equivalente",   format: "percent", color: "green" },
    bottomLeft: { label: "Riesgo",       field: "risk_score",        format: "score",   color: "amber" },
    bottomRight:{ label: "NOI",          field: "ingreso_neto_anual",format: "currency",color: "green" },
  },
  GREENFIELD: {
    topLeft:    { label: "TIR",          field: "irr_equivalente",   format: "percent", color: "green" },
    bottomLeft: { label: "Riesgo",       field: "risk_score",        format: "score",   color: "amber" },
    bottomRight:{ label: "Margen",       field: "roiTotal",          format: "percent", color: "green" },
  },
  LIVESTOCK: {
    topLeft:    { label: "Yield",        field: "irr_equivalente",   format: "percent", color: "amber" },
    bottomLeft: { label: "Riesgo",       field: "risk_score",        format: "score",   color: "amber" },
    bottomRight:{ label: "Renta/año",    field: "ingreso_neto_anual",format: "currency",color: "amber" },
  },
  FORESTRY: {
    topLeft:    { label: "TIR",          field: "irr_equivalente",   format: "percent", color: "green" },
    bottomLeft: { label: "Riesgo",       field: "risk_score",        format: "score",   color: "amber" },
    bottomRight:{ label: "Horizonte",    field: "horizonte_anos",    format: "number",  color: "white" },
  },
  BUY_AND_HOLD: {
    topLeft:    { label: "Cap Rate",     field: "irr_equivalente",   format: "percent", color: "green" },
    bottomLeft: { label: "Riesgo",       field: "risk_score",        format: "score",   color: "amber" },
    bottomRight:{ label: "NOI",          field: "ingreso_neto_anual",format: "currency",color: "green" },
  },
};

export const FINANCIAL_VARS_CONFIG: Record<string, Array<{
  label: string; field: string; format: string; positive?: string; showBar?: boolean; barMax?: number; delta?: string;
}>> = {
  FIX_FLIP: [
    { label: "Precio compra",  field: "precio_usd",            format: "currency" },
    { label: "CapEx reforma",  field: "capex_estimado",         format: "currency", positive: "low" },
    { label: "ARV estimado",   field: "arv_estimado",           format: "currency", positive: "high" },
    { label: "ROI total",      field: "roiTotal",               format: "percent",  positive: "high", showBar: true, barMax: 1 },
    { label: "IRR equiv.",     field: "irr_equivalente",        format: "percent",  positive: "high", showBar: true, barMax: 0.4 },
    { label: "Payback",        field: "payback_meses",          format: "number",   positive: "low" },
    { label: "Precio m²",      field: "precio_m2",              format: "currency", delta: "precio_m2_zona" },
    { label: "Confidence",     field: "confidence_final",       format: "percent",  showBar: true, barMax: 1 },
  ],
  RENTA: [
    { label: "Precio activo",  field: "precio_usd",             format: "currency" },
    { label: "Renta mensual",  field: "renta_mensual",          format: "currency", positive: "high" },
    { label: "Cap Rate",       field: "irr_equivalente",        format: "percent",  positive: "high", showBar: true, barMax: 0.15 },
    { label: "NOI anual",      field: "ingreso_neto_anual",     format: "currency", positive: "high" },
    { label: "Vacancia est.",  field: "vacancia_pct",           format: "percent",  positive: "low",  showBar: true, barMax: 0.3 },
    { label: "OPEX anual",     field: "opex_anual",             format: "currency", positive: "low" },
    { label: "IRR 10 años",    field: "irr_equivalente",        format: "percent",  positive: "high" },
    { label: "Confidence",     field: "confidence_final",       format: "percent",  showBar: true, barMax: 1 },
  ],
  RENTAL_LONG_TERM: [
    { label: "Precio activo",  field: "precio_usd",             format: "currency" },
    { label: "Renta mensual",  field: "renta_mensual",          format: "currency", positive: "high" },
    { label: "Cap Rate",       field: "irr_equivalente",        format: "percent",  positive: "high", showBar: true, barMax: 0.15 },
    { label: "NOI anual",      field: "ingreso_neto_anual",     format: "currency", positive: "high" },
    { label: "Vacancia est.",  field: "vacancia_pct",           format: "percent",  positive: "low" },
    { label: "OPEX anual",     field: "opex_anual",             format: "currency", positive: "low" },
    { label: "IRR 10 años",    field: "irr_equivalente",        format: "percent",  positive: "high" },
    { label: "Confidence",     field: "confidence_final",       format: "percent",  showBar: true, barMax: 1 },
  ],
  FARMLAND: [
    { label: "Valor campo",    field: "precio_usd",             format: "currency" },
    { label: "Superficie",     field: "superficie_ha",          format: "number" },
    { label: "Renta arrend.",  field: "ingreso_neto_anual",     format: "currency", positive: "high" },
    { label: "Yield agro",     field: "irr_equivalente",        format: "percent",  positive: "high", showBar: true, barMax: 0.12 },
    { label: "Cap rate",       field: "cap_rate",               format: "percent",  positive: "high" },
    { label: "OPEX agro",      field: "opex_anual",             format: "currency", positive: "low" },
    { label: "IRR 15 años",    field: "irr_equivalente",        format: "percent",  positive: "high" },
    { label: "Confidence",     field: "confidence_final",       format: "percent",  showBar: true, barMax: 1 },
  ],
  DISTRESS: [
    { label: "Precio oferta",  field: "precio_usd",             format: "currency" },
    { label: "Tasación",       field: "arv_estimado",           format: "currency" },
    { label: "Descuento",      field: "descuento_pct",          format: "percent",  positive: "high" },
    { label: "CapEx legal",    field: "capex_estimado",         format: "currency", positive: "low" },
    { label: "IRR proyect.",   field: "irr_equivalente",        format: "percent",  positive: "high", showBar: true, barMax: 0.4 },
    { label: "Payback",        field: "payback_meses",          format: "number",   positive: "low" },
    { label: "Upside total",   field: "roiTotal",               format: "percent",  positive: "high" },
    { label: "Confidence",     field: "confidence_final",       format: "percent",  showBar: true, barMax: 1 },
  ],
  DISTRESSED: [
    { label: "Precio oferta",  field: "precio_usd",             format: "currency" },
    { label: "Tasación",       field: "arv_estimado",           format: "currency" },
    { label: "Descuento",      field: "descuento_pct",          format: "percent",  positive: "high" },
    { label: "CapEx legal",    field: "capex_estimado",         format: "currency", positive: "low" },
    { label: "IRR proyect.",   field: "irr_equivalente",        format: "percent",  positive: "high" },
    { label: "Payback",        field: "payback_meses",          format: "number",   positive: "low" },
    { label: "Upside total",   field: "roiTotal",               format: "percent",  positive: "high" },
    { label: "Confidence",     field: "confidence_final",       format: "percent",  showBar: true, barMax: 1 },
  ],
  VALUE_ADD: [
    { label: "Precio compra",  field: "precio_usd",             format: "currency" },
    { label: "CapEx mejora",   field: "capex_estimado",         format: "currency", positive: "low" },
    { label: "NOI post-obra",  field: "ingreso_neto_anual",     format: "currency", positive: "high" },
    { label: "Cap Rate final", field: "irr_equivalente",        format: "percent",  positive: "high" },
    { label: "ROI total",      field: "roiTotal",               format: "percent",  positive: "high" },
    { label: "Payback",        field: "payback_meses",          format: "number",   positive: "low" },
    { label: "Upside",         field: "roiTotal",               format: "percent",  positive: "high" },
    { label: "Confidence",     field: "confidence_final",       format: "percent",  showBar: true, barMax: 1 },
  ],
  LAND_BANKING: [
    { label: "Precio tierra",  field: "precio_usd",             format: "currency" },
    { label: "Superficie",     field: "superficie_ha",          format: "number" },
    { label: "Precio m²",      field: "precio_m2",              format: "currency" },
    { label: "Apreciación",    field: "irr_equivalente",        format: "percent",  positive: "high" },
    { label: "Horizonte",      field: "horizonte_anos",         format: "number" },
    { label: "OPEX",           field: "opex_anual",             format: "currency", positive: "low" },
    { label: "IRR",            field: "irr_equivalente",        format: "percent",  positive: "high" },
    { label: "Confidence",     field: "confidence_final",       format: "percent",  showBar: true, barMax: 1 },
  ],
  SHORT_TERM_RENTAL: [
    { label: "Precio activo",  field: "precio_usd",             format: "currency" },
    { label: "ADR",            field: "renta_mensual",          format: "currency", positive: "high" },
    { label: "RevPAR",         field: "irr_equivalente",        format: "percent",  positive: "high" },
    { label: "Ocupación",      field: "ocupacion_pct",          format: "percent",  positive: "high", showBar: true, barMax: 1 },
    { label: "NOI anual",      field: "ingreso_neto_anual",     format: "currency", positive: "high" },
    { label: "OPEX + fees",    field: "opex_anual",             format: "currency", positive: "low" },
    { label: "Cap Rate",       field: "irr_equivalente",        format: "percent",  positive: "high" },
    { label: "Confidence",     field: "confidence_final",       format: "percent",  showBar: true, barMax: 1 },
  ],
  NNN_COMERCIAL: [
    { label: "Precio activo",  field: "precio_usd",             format: "currency" },
    { label: "Renta mensual",  field: "renta_mensual",          format: "currency", positive: "high" },
    { label: "Cap Rate",       field: "irr_equivalente",        format: "percent",  positive: "high", showBar: true, barMax: 0.1 },
    { label: "NOI",            field: "ingreso_neto_anual",     format: "currency", positive: "high" },
    { label: "DSCR",           field: "dscr",                   format: "number",   positive: "high" },
    { label: "LTV",            field: "ltv_pct",                format: "percent",  positive: "low" },
    { label: "IRR",            field: "irr_equivalente",        format: "percent",  positive: "high" },
    { label: "Confidence",     field: "confidence_final",       format: "percent",  showBar: true, barMax: 1 },
  ],
  GREENFIELD: [
    { label: "Precio suelo",   field: "precio_usd",             format: "currency" },
    { label: "Superficie",     field: "superficie_ha",          format: "number" },
    { label: "CapEx desarrollo",field:"capex_estimado",         format: "currency", positive: "low" },
    { label: "GDV estimado",   field: "arv_estimado",           format: "currency", positive: "high" },
    { label: "ROI desarrollo", field: "roiTotal",               format: "percent",  positive: "high" },
    { label: "Horizonte",      field: "horizonte_anos",         format: "number" },
    { label: "IRR",            field: "irr_equivalente",        format: "percent",  positive: "high" },
    { label: "Confidence",     field: "confidence_final",       format: "percent",  showBar: true, barMax: 1 },
  ],
  LIVESTOCK: [
    { label: "Valor campo",    field: "precio_usd",             format: "currency" },
    { label: "Superficie",     field: "superficie_ha",          format: "number" },
    { label: "Renta arrend.",  field: "ingreso_neto_anual",     format: "currency", positive: "high" },
    { label: "Yield",          field: "irr_equivalente",        format: "percent",  positive: "high" },
    { label: "Carga animal",   field: "carga_animal",           format: "number" },
    { label: "OPEX",           field: "opex_anual",             format: "currency", positive: "low" },
    { label: "IRR",            field: "irr_equivalente",        format: "percent",  positive: "high" },
    { label: "Confidence",     field: "confidence_final",       format: "percent",  showBar: true, barMax: 1 },
  ],
  FORESTRY: [
    { label: "Precio tierra",  field: "precio_usd",             format: "currency" },
    { label: "Superficie",     field: "superficie_ha",          format: "number" },
    { label: "Especie",        field: "especie_forestal",       format: "text" },
    { label: "Horizonte",      field: "horizonte_anos",         format: "number" },
    { label: "Renta arrend.",  field: "ingreso_neto_anual",     format: "currency", positive: "high" },
    { label: "OPEX",           field: "opex_anual",             format: "currency", positive: "low" },
    { label: "IRR",            field: "irr_equivalente",        format: "percent",  positive: "high" },
    { label: "Confidence",     field: "confidence_final",       format: "percent",  showBar: true, barMax: 1 },
  ],
  BUY_AND_HOLD: [
    { label: "Precio activo",  field: "precio_usd",             format: "currency" },
    { label: "Renta mensual",  field: "renta_mensual",          format: "currency", positive: "high" },
    { label: "Cap Rate",       field: "irr_equivalente",        format: "percent",  positive: "high" },
    { label: "NOI anual",      field: "ingreso_neto_anual",     format: "currency", positive: "high" },
    { label: "Apreciación",    field: "apreciacion_anual",      format: "percent",  positive: "high" },
    { label: "OPEX",           field: "opex_anual",             format: "currency", positive: "low" },
    { label: "IRR 10 años",    field: "irr_equivalente",        format: "percent",  positive: "high" },
    { label: "Confidence",     field: "confidence_final",       format: "percent",  showBar: true, barMax: 1 },
  ],
};
